const zoneData = {
  app: {
    sortCol: 'name',
    sortDir: 'asc',
    filterStr: '',
  },
  data: [
    {
      id: 1,
      name: 'Front Lawn',
      squareFeet: 2000,
      colorScheme: 'green',
      sunlight: 'full sun',
      diagram: './images/popover/frontlawn.jpg',
      alt: 'front lawn is located on the east side of the house',
    },
    {
      id: 2,
      name: 'Front Borders',
      squareFeet: 1500,
      colorScheme: 'mixed',
      sunlight: 'full sun',
      diagram: 'images/popover/frontborders.jpg',
      alt: 'front borders surround the front lawn on the east side of the house',
    },
    {
      id: 4,
      name: 'North Side',
      squareFeet: 1900,
      colorScheme: 'green',
      sunlight: 'shade',
      diagram: 'images/popover/northside.jpg',
      alt: 'this is a narrow strip on the north side of the house',
    },
    {
      id: 5,
      name: 'South Side',
      squareFeet: 1500,
      colorScheme: 'yellow',
      sunlight: 'part sun',
      diagram: 'images/popover/southside.jpg',
      alt: 'south side is located at the south east of the property',
    },
    {
      id: 6,
      name: 'Berry Beds',
      squareFeet: 600,
      colorScheme: 'green',
      sunlight: 'full sun',
      diagram: 'images/popover/berrybeds.jpg',
      alt: 'the berry beds are south of the driveway, back towards the garage',
    },
    {
      id: 7,
      name: 'Back Lawn',
      squareFeet: 808,
      colorScheme: 'green',
      sunlight: 'full sun',
      diagram: 'images/popover/backlawn.jpg',
      alt: 'the back lawn in centered in the backyard, west of the house',
    },
    {
      id: 8,
      name: 'Back Raised Bed',
      squareFeet: 400,
      colorScheme: 'green',
      sunlight: 'full sun',
      diagram: 'images/popover/backraised.jpg',
      alt: 'the back raised beds are on the northern side of the backyard',
    },
    {
      id: 9,
      name: 'Back Borders',
      squareFeet: 600,
      colorScheme: 'green',
      sunlight: 'full sun',
      diagram: 'images/popover/backborders.jpg',
      alt: 'the backborders surround the backyard',
    },
    {
      id: 10,
      name: 'Back Trellis',
      squareFeet: 80,
      colorScheme: 'jewel tones',
      sunlight: 'full sun',
      diagram: 'images/popover/backtrellis.jpg',
      alt: 'the back trellis is against the west wall of the house to protect it from hot summer sun',
    },
    {
      id: 11,
      name: 'Pond',
      squareFeet: 70,
      colorScheme: 'pinks',
      sunlight: 'full sun',
      diagram: 'images/popover/pond.jpg',
      alt: 'the pond is located in the north east section of the back yard',
    },
  ],
};

export default zoneData;
